# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from demo.users.v1 import users_pb2 as demo_dot_users_dot_v1_dot_users__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in demo/users/v1/users_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/demo.users.v1.UserService/GetUser',
                request_serializer=demo_dot_users_dot_v1_dot_users__pb2.GetUserRequest.SerializeToString,
                response_deserializer=demo_dot_users_dot_v1_dot_users__pb2.GetUserResponse.FromString,
                _registered_method=True)
        self.WatchUsers = channel.unary_stream(
                '/demo.users.v1.UserService/WatchUsers',
                request_serializer=demo_dot_users_dot_v1_dot_users__pb2.WatchUsersRequest.SerializeToString,
                response_deserializer=demo_dot_users_dot_v1_dot_users__pb2.UserEvent.FromString,
                _registered_method=True)
        self.UploadUsers = channel.stream_unary(
                '/demo.users.v1.UserService/UploadUsers',
                request_serializer=demo_dot_users_dot_v1_dot_users__pb2.User.SerializeToString,
                response_deserializer=demo_dot_users_dot_v1_dot_users__pb2.UploadUsersResponse.FromString,
                _registered_method=True)
        self.SyncUsers = channel.stream_stream(
                '/demo.users.v1.UserService/SyncUsers',
                request_serializer=demo_dot_users_dot_v1_dot_users__pb2.UserCommand.SerializeToString,
                response_deserializer=demo_dot_users_dot_v1_dot_users__pb2.UserEvent.FromString,
                _registered_method=True)


class UserServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetUser(self, request, context):
        """Unary: one request -> one response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchUsers(self, request, context):
        """Server streaming: one request -> long-lived stream of events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadUsers(self, request_iterator, context):
        """Client streaming: many users -> one summary response after client closes its send side.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncUsers(self, request_iterator, context):
        """Bidirectional streaming: both sides keep their streams open.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=demo_dot_users_dot_v1_dot_users__pb2.GetUserRequest.FromString,
                    response_serializer=demo_dot_users_dot_v1_dot_users__pb2.GetUserResponse.SerializeToString,
            ),
            'WatchUsers': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchUsers,
                    request_deserializer=demo_dot_users_dot_v1_dot_users__pb2.WatchUsersRequest.FromString,
                    response_serializer=demo_dot_users_dot_v1_dot_users__pb2.UserEvent.SerializeToString,
            ),
            'UploadUsers': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadUsers,
                    request_deserializer=demo_dot_users_dot_v1_dot_users__pb2.User.FromString,
                    response_serializer=demo_dot_users_dot_v1_dot_users__pb2.UploadUsersResponse.SerializeToString,
            ),
            'SyncUsers': grpc.stream_stream_rpc_method_handler(
                    servicer.SyncUsers,
                    request_deserializer=demo_dot_users_dot_v1_dot_users__pb2.UserCommand.FromString,
                    response_serializer=demo_dot_users_dot_v1_dot_users__pb2.UserEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo.users.v1.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('demo.users.v1.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.users.v1.UserService/GetUser',
            demo_dot_users_dot_v1_dot_users__pb2.GetUserRequest.SerializeToString,
            demo_dot_users_dot_v1_dot_users__pb2.GetUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/demo.users.v1.UserService/WatchUsers',
            demo_dot_users_dot_v1_dot_users__pb2.WatchUsersRequest.SerializeToString,
            demo_dot_users_dot_v1_dot_users__pb2.UserEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadUsers(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/demo.users.v1.UserService/UploadUsers',
            demo_dot_users_dot_v1_dot_users__pb2.User.SerializeToString,
            demo_dot_users_dot_v1_dot_users__pb2.UploadUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncUsers(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/demo.users.v1.UserService/SyncUsers',
            demo_dot_users_dot_v1_dot_users__pb2.UserCommand.SerializeToString,
            demo_dot_users_dot_v1_dot_users__pb2.UserEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
